using Microsoft.AspNetCore.Mvc;
using MongoDB.Driver;
using WFM.Infrastructure.Persistence.MongoDB;
using WFM.Infrastructure.Persistence.MongoDB.Documents;

namespace WFM.API.Controllers;

[ApiController]
[Route("api/v1/[controller]")]
public class ReportsController : ControllerBase
{
    private readonly MongoDbContext _mongoContext;

    public ReportsController(MongoDbContext mongoContext)
    {
        _mongoContext = mongoContext;
    }

    // GET /api/v1/reports/summary/latest
    // Returns the most recent summary report generated by Worker 2
    [HttpGet("summary/latest")]
    public async Task<IActionResult> GetLatestSummary()
    {
        var report = await _mongoContext.SummaryReports
            .Find(_ => true)
            .SortByDescending(r => r.GeneratedAt)
            .FirstOrDefaultAsync();

        if (report is null) return NotFound("No reports generated yet.");
        return Ok(report);
    }

    // GET /api/v1/reports/summary
    // Returns all summary reports
    [HttpGet("summary")]
    public async Task<IActionResult> GetAllSummaries()
    {
        var reports = await _mongoContext.SummaryReports
            .Find(_ => true)
            .SortByDescending(r => r.GeneratedAt)
            .Limit(10)
            .ToListAsync();

        return Ok(reports);
    }
}
